Repository AY1920S1-CS2113-T13-2/main, pull requests merged in 2019-11, with the labels that each got.

#254 fix the bug that a user will get error for assigning period task
  data/patientsTasks.csv
  src/main/java/duke/models/assignedtasks/AssignedTaskWithPeriod.java
Labels: priority.Medium

#255 Fixed a redundant if condition in a AssignedTaskWithPeriod constructor
  src/main/java/duke/models/assignedtasks/AssignedTaskWithPeriod.java
Labels: priority.Low

#264 Upcoming Tasks (GUI)
  data/patientsTasks.csv
  src/main/java/duke/commands/CommandManager.java
  src/main/java/duke/commands/task/UpcomingTasksCommand.java
  src/main/java/duke/gui/MainWindow.java
  src/main/java/duke/gui/UpcomingTasksBox.java
  src/main/java/duke/models/assignedtasks/UpcomingTasks.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UpcomingTaskBox.fxml
Labels: type.Enhancement

#265 Populating data and fixing bug within UpcomingTasks's GUI portion
  data/patientsTasks.csv
  data/standardTasks.csv
  src/main/java/duke/gui/MainWindow.java
Labels: type.Bug, type.Enhancement

#271 Dynamic Update for Upcoming Tasks GUI + JUnits for ParserTest, CommandManager, and HelpCommand
  src/main/java/duke/commands/CommandManager.java
  src/main/java/duke/commands/functional/HelpCommand.java
  src/main/java/duke/gui/MainWindow.java
  src/test/java/duke/commands/CommandManagerTest.java
  src/test/java/duke/commands/HelpCommandTest.java
  src/test/java/duke/util/ParserTest.java
Labels: type.Enhancement

#280 add junit test for assignedTaskManager and mementoManager
  src/test/java/duke/models/assignedtasks/AssignedTaskManagerTest.java
  src/test/java/duke/util/mementopattern/MementoManagerTest.java
Labels: priority.Low

#290 Fixed the bug which user cant undo the updatePatient and Task Command
  src/main/java/duke/commands/patient/UpdatePatientCommand.java
  src/main/java/duke/commands/task/UpdateTaskCommand.java
Labels: priority.High

#296 Pre-populating Data when data files are empty
  src/main/java/duke/Duke.java
  src/main/java/duke/Main.java
  src/main/java/duke/util/StartUpData.java
Labels: type.Enhancement
