Repository AY1920S1-CS2113-T13-2/main, pull requests merged in 2019-10, with the labels that each got.

#107 Add in the FindPatientTaskcommand
  data/standardTasks.csv
  src/main/java/duke/Duke.java
  src/main/java/duke/command/AssignTaskToPatientCommand.java
  src/main/java/duke/command/FindPatientTaskCommand.java
  src/main/java/duke/core/CommandManager.java
  src/main/java/duke/core/Ui.java
  src/main/java/duke/relation/EventPatientTask.java
  src/main/java/duke/relation/PatientTaskList.java
Labels: priority.High, type.Enhancement

#121 Complete version of the Patient & Task Relation (Assign,Delete by unique ID, Find)
  build/reports/checkstyle/main.html
  build/reports/checkstyle/main.xml
  build/reports/checkstyle/test.html
  build/reports/checkstyle/test.xml
  data/patients.csv
  data/patientsTasks.csv
  data/standardTasks.csv
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/duke/Duke.java
  src/main/java/duke/command/AssignTaskToPatientCommand.java
  src/main/java/duke/command/DeletePatientTaskCommand.java
  src/main/java/duke/command/FindPatientTaskCommand.java
  src/main/java/duke/core/CommandManager.java
  src/main/java/duke/core/Parser.java
  src/main/java/duke/core/Ui.java
  src/main/java/duke/relation/EventPatientTask.java
  src/main/java/duke/relation/PatientTask.java
  src/main/java/duke/relation/PatientTaskList.java
  src/main/java/duke/relation/StandardPatientTask.java
  src/main/java/duke/storage/PatientTaskStorage.java
  src/test/java/duke/core/ParserTest.java
Labels: priority.Medium

#159 Improving Parser/CommandManager flexibility
  src/main/java/duke/command/FindPatientCommand.java
  src/main/java/duke/command/UpdatePatientCommand.java
  src/main/java/duke/command/UpdateTaskCommand.java
  src/main/java/duke/core/CommandManager.java
  src/main/java/duke/core/Parser.java
  src/test/java/duke/core/CommandManagerTest.java
  src/test/java/duke/core/ParserTest.java
Labels: type.Enhancement

#149 This update gives the user a new function to remove all the tasks ass…
  src/main/java/duke/command/AssignTaskToPatientCommand.java
  src/main/java/duke/command/DeletePatientCommand.java
  src/main/java/duke/command/DeletePatientTaskCommand.java
  src/main/java/duke/command/FindPatientTaskCommand.java
  src/main/java/duke/core/Ui.java
  src/main/java/duke/relation/EventPatientTask.java
  src/main/java/duke/relation/PatientTaskList.java
  src/main/java/duke/relation/StandardPatientTask.java
Labels: priority.Medium

#190 BUG fix on some critical problems & data structure improvement
  src/main/java/duke/commands/assignedtask/AssignDeadlineTaskCommand.java
  src/main/java/duke/commands/assignedtask/AssignPeriodTaskCommand.java
  src/main/java/duke/commands/assignedtask/DeleteAssignedTaskCommand.java
  src/main/java/duke/commands/assignedtask/FindAssignedTaskCommand.java
  src/main/java/duke/models/assignedtasks/AssignedTask.java
  src/main/java/duke/models/assignedtasks/AssignedTaskManager.java
  src/main/java/duke/models/assignedtasks/AssignedTaskWithDate.java
  src/main/java/duke/models/assignedtasks/AssignedTaskWithPeriod.java
  src/main/java/duke/storages/StorageManager.java
  src/main/java/duke/util/mementopattern/MementoManager.java
  src/main/java/duke/util/mementopattern/MementoParser.java
Labels: priority.High

#202 Help Guide Improvements
  src/main/java/duke/commands/functional/HelpCommand.java
  src/main/java/duke/gui/HelpBox.java
  src/main/java/duke/gui/MainWindow.java
  src/main/java/duke/util/Ui.java
  src/main/resources/view/HelpBox.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement
